Feature/cli 2220 mascarar dados no dump
Climba-Commerce/MySQL-dump pull request #1
Opened 2023-09-08 18:36 UTC by Jhon-Henkel

2023-09-08 20:17 UTC, idealizetecnologia requested changes

2023-09-08 20:17 UTC, idealizetecnologia commented on Dockerfile
> +FROM php:7.1-fpm
Colocar na 7.2

2023-09-08 20:17 UTC, idealizetecnologia commented on composer.json
> +		"mockery/mockery": "^1.3"
Colocar no require-dev

2023-09-08 20:17 UTC, idealizetecnologia commented on composer.json
> +		"phpunit/phpunit": "^7.5"
Colocar na versão ^8

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +use MySQLDump\mask\IMaskValue;
Colocar o mask em maiusculo

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +    private $maskData = [];
maskCollection ou maskList

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +                $s = '(';
Converte para space

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +        return $mask ? $mask->maskValue() : $value;
Acho melhor passar o paramentro value

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +        $this->maskData[$table][$column] = $mask;
Faltou declarar o array da tabela

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +            foreach ($this->maskData[$tableMask] as $columnMask => $mask) {
Fazer por isset

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLDump.php
> +        $this->maskData[$table][$column] = $mask;
Colocar a chave do array já com o normalize

2023-09-08 20:17 UTC, idealizetecnologia commented on src/MySQLImport.php
>   *
Validar  se o idcommerce está usando esse projeto

2023-09-08 20:17 UTC, idealizetecnologia commented on composer.json
> +		"phpunit/phpunit": "^7.5"
Acho que a melhor forma é usar o '*'

2023-09-11 11:14 UTC, Jhon-Henkel commented on src/MySQLImport.php
>   *
Tem somente no composer.json um script:

```
"phpmd:html": "RodaMySQLDump o PHP-MD e gera relatório em .html",
```

2023-09-11 11:48 UTC, Jhon-Henkel commented on src/MySQLImport.php
>   *
Não usa a classe MySQLDump em nenhum local do idcommerce.

2023-09-12 17:23 UTC, merged